### ISSUE TITLE
Mlb 2019 the show

### ISSUE THREAD

**Issue by stmurray333** [cardona150/MlbTheShow18MarketAssistant#19]
Will you be creating this extension to work with MLB 2019?  I loved the 2018 one....

**Comment by cardona150** [comment]
No I only casually played last year because my wife bought 18. I made the assistant to make coins for her to buy gear :P Then I decided to share it. If she buys 19 I might take a stab at it. You can find all the code I wrote here. It was based off https://github.com/AnthoneyKalasho this person seems to make something every year.
